export const actionIds = {
  SUBMIT_TRACK: 'SUBMIT_TRACK',
  SUBMIT_TRACK_RESPONSE: 'SUBMIT_TRACK_RESPONSE',
  UPLOAD_IMAGE: 'UPLOAD_IMAGE',
  UPLOAD_IMAGE_RESPONSE: 'UPLOAD_IMAGE_RESPONSE',
  UPLOAD_MUSIC: 'UPLOAD_MUSIC',
  UPLOAD_MUSIC_RESPONSE: 'UPLOAD_MUSIC_RESPONSE',
  LOGIN_CALL: 'LOGIN_CALL',
  LOGIN_RESPONSE: 'LOGIN_RESPONSE',
  GOOGLE_CALL: 'GOOGLE_CALL',
  GOOGLE_RESPONSE: 'GOOGLE_RESPONSE',
  SNAPCHAT_CALL: 'SNAPCHAT_CALL',
  SNAPCHAT_RESPONSE: 'SNAPCHAT_RESPONSE',
  FACEBOOK_CALL: 'FACEBOOK_CALL',
  FACEBOOK_RESPONSE: 'FACEBOOK_RESPONSE',
  SIGNUP_CALL: 'SIGNUP_CALL',
  SIGNUP_RESPONSE: 'SIGNUP_RESPONSE',
  FORGOTPASSWORD_CALL: 'FORGOTPASSWORD_CALL',
  FORGOTPASSWORD_RESPONSE: 'FORGOTPASSWORD_RESPONSE',
  RESETPASSWORD_CALL: ' RESETPASSWORD_CALL',
  RESETPASSWORD_RESPONSE: ' RESETPASSWORD_RESPONSE',

  SEND_DATA: 'SEND_DATA',
  SEND_DATA_RESPONSE: 'SEND_DATA_RESPONSE',

  SEND_SNAP_DATA: 'SEND_SNAP_DATA',
  SEND_SNAP_DATA_RESPONSE: 'SEND_SNAP_DATA_RESPONSE',

  MUSIC_CONSTANT: 'MUSIC_CONSTANT',
  MUSIC_CONSTANT_RESPONSE: 'MUSIC_CONSTANT_RESPONSE',

  IMAGE_CONSTANT: 'IMAGE_CONSTANT',
  IMAGE_CONSTANT_RESPONSE: 'IMAGE_CONSTANT_RESPONSE',

  MUSIC_TRIM_CONSTANT: 'MUSIC_TRIM_CONSTANT',
  MUSIC_TRIM_CONSTANT_RESPONSE: 'MUSIC_TRIM_CONSTANT_RESPONSE',

  SUBMIT_DATA: 'SUBMIT_DATA',
  SUBMIT_DATA_RESPONSE: 'SUBMIT_DATA_RESPONSE',

  POST_COPYRIGHT: 'POST_COPYRIGHT',
  POST_COPYRIGHT_RESPONSE: 'POST_COPYRIGHT_RESPONSE',

  NULL_BEAT: 'NULL_BEAT',
  NULL_BEAT_RESPONSE: 'NULL_BEAT_RESPONSE',
};
